spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helssm
    username: root
    password: e2e2e2
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
#  jooq:
#    sql-dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8088
debug: true

#logging:
#  level.org.hibernate.SQL: debug

##thymeleaf start
#spring.thymeleaf.mode=HTML5
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.content-type=text/html
##开发时关闭缓存,不然没法看到实时页面
#spring.thymeleaf.cache=false
##thymeleaf end